force-app/main/default/objects/House_Member__c/House_Member__c.object-meta.xml
<CustomObject>
    <label>House Member</label>
    <nameField>
        <label>House Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>House Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/House_Member__c/fields/Car_Type__c.field-meta.xml
<CustomField>
    <fullName>Car_Type__c</fullName>
    <label>Car Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sedan,</fullName>
            </value>
            <value>
                <fullName>SUV,</fullName>
            </value>
            <value>
                <fullName>Truck,</fullName>
            </value>
            <value>
                <fullName>Coop,</fullName>
            </value>
            <value>
                <fullName>Luxury</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/House_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>House Members</relationshipLabel>
    <relationshipName>House_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/House_Member__c/fields/Insured__c.field-meta.xml
<CustomField>
    <fullName>Insured__c</fullName>
    <label>Insured?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/House_Member__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tesla,</fullName>
            </value>
            <value>
                <fullName>Toyota,</fullName>
            </value>
            <value>
                <fullName>Subaru,</fullName>
            </value>
            <value>
                <fullName>Chevy,</fullName>
            </value>
            <value>
                <fullName>Ford,</fullName>
            </value>
            <value>
                <fullName>Lincoln,</fullName>
            </value>
            <value>
                <fullName>Cadillac,</fullName>
            </value>
            <value>
                <fullName>Honda,</fullName>
            </value>
            <value>
                <fullName>Hyundai,</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/vehicleController.cls
public without sharing class vehicleController {
    
    @AuraEnabled(Cacheable=true)
    public static List<House_Member__c> getVehicle(String recordId){
     

        return [
            SELECT
              Id,
              Name,
              Make__c,
              Car_Type__c,
              Model__c,
              Color__c,
              Insured__c
            FROM House_Member__c
            WHERE Contact__c = :recordId AND RecordTypeId = '0128b000000dO04AAE'
          ];
    }

    @AuraEnabled(Cacheable=true)
    public static String getContactId(String userId){
      List<User> userRecord = [SELECT Contact.Id FROM User WHERE Id=: userId LIMIT 1];
      String contactIdPassing;
        
      for (User us : userRecord) {
        contactIdPassing = us.Contact.Id;
      }
      return contactIdPassing;
    }
}