force-app/main/default/objects/Image/fields/Image_Type__c.field-meta.xml
<CustomField>
    <fullName>Image_Type__c</fullName>
    <label>Image Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Main</fullName>
            </value>
            <value>
                <fullName>Sub</fullName>
            </value>
            <value>
                <fullName>Unit</fullName>
            </value>
            <value>
                <fullName>Floor Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Image/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Images</relationshipLabel>
    <relationshipName>Images</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ImageController.cls
/**
 * ImageController.cls
 * Author(s): Dorian Alexander Patterson
 *
 * Returns a response with all images related to a property that are not floor plan images.
 */
public with sharing class ImageController {
    @AuraEnabled(cacheable=true)
    public static List<Image> getImagesNotFloorPlan(String recordId){
        try {
            return [
                SELECT URL
                FROM Image
                WHERE Property__c = :recordId AND
                Image_Type__c != 'Floor Plan'
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}